places_to_search = [
    "tokyo japan", 
    "manila philippines", 
    "paris france",
    "new york usa",
     "sydney australia",
    "cape town south africa",
    "london uk",
    "rio de janeiro brazil",
    "beijing china",
    "rome italy",
    "moscow russia",
    "dubai uae",
    "toronto canada",
    "berlin germany",
    "madrid spain",
    "bangkok thailand",
    "seoul south korea",
    "cairo egypt",
    "istanbul turkey",
    "mexico city mexico",
    "buenos aires argentina",
    "mumbai india",
    "jakarta indonesia",
    "nairobi kenya",
    "singapore singapore",
    "lisbon portugal",
    "amsterdam netherlands",
    "vienna austria",
     "zurich switzerland",
    "athens greece",
    "prague czech republic",
    "helsinki finland",
    "oslo norway"
]
